import { withAlpha, type PanelLayout, type PanelTheme } from "./tools";

export function buildPanelStyles(theme: PanelTheme, layout: PanelLayout) {
  const c = theme.colors;
  const compact = layout.compact;
  const space = compact ? 8 : 12;
  const controlHeight = compact ? 40 : 36;
  return {
    root: { flex: 1, backgroundColor: c.surface0 },
    content: { padding: compact ? 8 : 16, gap: space },
    desktopShell: { flexGrow: 1, padding: 16, gap: 12 },
    contextBar: {
      gap: 8,
      paddingBottom: 12,
      backgroundColor: c.surface0,
      borderBottomWidth: 1,
      borderBottomColor: withAlpha(c.foregroundMuted, 0.18),
    },
    contextTop: { flexDirection: "row", alignItems: "center", gap: 8, flexWrap: "wrap" },
    contextActions: { marginLeft: "auto", flexDirection: "row", alignItems: "center", gap: 8, flexWrap: "wrap" },
    contextMeta: { flexDirection: "row", alignItems: "stretch", gap: compact ? 8 : 16, flexWrap: "wrap" },
    contextSelector: { minWidth: compact ? 160 : 220, flexGrow: 1 },
    contextItem: { minWidth: compact ? 120 : 148, gap: 2 },
    contextLabel: { color: c.foregroundMuted, fontSize: 10, fontWeight: "700", textTransform: "uppercase", letterSpacing: 0.5 },
    contextValue: { color: c.foreground, fontSize: compact ? 11.5 : 12.5, lineHeight: compact ? 16 : 18, fontWeight: "600" },
    title: { color: c.foreground, fontSize: compact ? 19 : 24, lineHeight: compact ? 24 : 30, fontWeight: "800", letterSpacing: -0.3 },
    statusPill: { backgroundColor: withAlpha(c.accent, 0.1), borderRadius: 999, paddingHorizontal: 8, paddingVertical: 3 },
    statusPillDanger: { backgroundColor: withAlpha(c.statusDanger, 0.1) },
    statusPillText: { color: c.accent, fontSize: 10, fontWeight: "700", textTransform: "uppercase", letterSpacing: 0.4 },
    statusPillTextDanger: { color: c.statusDanger },
    topButton: {
      minHeight: controlHeight,
      borderWidth: 1,
      borderColor: withAlpha(c.foregroundMuted, 0.3),
      borderRadius: 8,
      paddingHorizontal: compact ? 10 : 12,
      justifyContent: "center",
      alignItems: "center",
    },
    queueButton: { borderColor: withAlpha(c.accent, 0.55), backgroundColor: withAlpha(c.accent, 0.06) },
    topButtonText: { color: c.foregroundMuted, fontSize: 11.5, fontWeight: "600" },
    queueButtonText: { color: c.accent, fontSize: 11.5, fontWeight: "700" },
    staleStrip: { backgroundColor: withAlpha(c.accent, 0.08), borderLeftWidth: 2, borderLeftColor: c.accent, borderRadius: 4, paddingVertical: 8, paddingHorizontal: 10 },
    staleStripText: { color: c.accent, fontSize: 11.5, fontWeight: "600", lineHeight: 16 },
    errorCard: { backgroundColor: withAlpha(c.statusDanger, 0.07), borderWidth: 1, borderColor: withAlpha(c.statusDanger, 0.32), borderRadius: 8, padding: 10 },
    errorText: { color: c.statusDanger, fontSize: 12, lineHeight: 17 },
    workbench: {
      flexDirection: "row",
      alignItems: "stretch",
      borderWidth: 1,
      borderColor: withAlpha(c.foregroundMuted, 0.18),
      borderRadius: 10,
      overflow: "hidden",
    },
    fileNavigator: {
      flexDirection: "column",
      width: compact ? "100%" : 304,
      alignSelf: compact ? undefined : "stretch",
      flexShrink: compact ? 1 : 0,
      minHeight: 0,
      overflow: "hidden",
      backgroundColor: withAlpha(c.foreground, 0.018),
      borderRightWidth: compact ? 0 : 1,
      borderRightColor: withAlpha(c.foregroundMuted, 0.18),
    },
    // Shared outer scroll: the navigator header and both section siblings
    // travel together and any content beyond the bounded pane height stays
    // reachable. The parent fileNavigator View carries the real height
    // (paneHeight on desktop, parent flex on compact), so this scroller is
    // bounded; the content container only lays out, never sizes children.
    fileNavigatorScroll: { flex: 1, minHeight: 0 },
    fileNavigatorContent: { flexDirection: "column", flexGrow: 1 },
    navigatorHeader: { flexShrink: 0, gap: 3, padding: compact ? 12 : 16, borderBottomWidth: 1, borderBottomColor: withAlpha(c.foregroundMuted, 0.16) },
    sectionEyebrow: { color: c.foregroundMuted, fontSize: 10.5, fontWeight: "700", textTransform: "uppercase", letterSpacing: 0.5 },
    sectionTitle: { color: c.foreground, fontSize: compact ? 14 : 16, lineHeight: compact ? 19 : 22, fontWeight: "700" },
    sectionSummary: { color: c.foregroundMuted, fontSize: 11, lineHeight: 15 },
    fileList: { paddingVertical: 4 },
    fileSection: { flexGrow: 0, flexShrink: 0 },
    fileSectionCollapsed: { flexGrow: 0, flexShrink: 0, flexBasis: "auto" },
    fileSectionScroll: compact
      ? { maxHeight: 320, flexGrow: 0 }
      : { flex: 1, minHeight: 0 },
    fileRow: { minHeight: compact ? 64 : 68, paddingHorizontal: compact ? 12 : 14, paddingVertical: 10, gap: 5, borderBottomWidth: 1, borderBottomColor: withAlpha(c.foregroundMuted, 0.12) },
    fileRowActive: { backgroundColor: withAlpha(c.accent, 0.08), borderLeftWidth: 3, borderLeftColor: c.accent, paddingLeft: compact ? 9 : 11 },
    fileRowTop: { flexDirection: "row", alignItems: "center", gap: 6 },
    filePath: { flex: 1, color: c.foreground, fontSize: compact ? 12.5 : 13, lineHeight: 18, fontWeight: "600" },
    fileMeta: { color: c.foregroundMuted, fontSize: 10.5, lineHeight: 15 },
    fileStatus: { color: c.foregroundMuted, fontSize: 10.5, fontWeight: "600" },
    fileStatusAccent: { color: c.accent },
    detailCanvas: { flex: compact ? 0 : 1, minWidth: 0, backgroundColor: c.surface0 },
    detailInner: { padding: 12, gap: compact ? 12 : 8 },
    commentArea: { flexShrink: 0 },
    backRow: { flexDirection: "row", alignItems: "center", gap: 8 },
    fileHeader: { flexShrink: 0, gap: 4, paddingBottom: 8, borderBottomWidth: 1, borderBottomColor: withAlpha(c.foregroundMuted, 0.16) },
    fileHeaderTop: { flexDirection: "row", alignItems: "center", gap: 8, flexWrap: "wrap" },
    fileHeaderPath: { flex: 1, minWidth: 180, color: c.foreground, fontSize: 16, lineHeight: compact ? 22 : 21, fontWeight: "700", letterSpacing: -0.15 },
    tagRow: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
    tagPill: { fontFamily: "monospace", fontSize: 10, lineHeight: 14, color: c.accent, backgroundColor: withAlpha(c.accent, 0.09), borderRadius: 999, paddingHorizontal: 6, paddingVertical: 2, flexShrink: 1, overflow: "hidden" },
    fileActionRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, alignItems: "center" },
    blockToolbar: { flexShrink: 0, gap: 4, paddingBottom: 8, borderBottomWidth: 1, borderBottomColor: withAlpha(c.foregroundMuted, 0.14) },
    blockNavigation: { flexDirection: "row", alignItems: "center", gap: 8 },
    blockPosition: { flex: 1, minWidth: 120, alignItems: "center", gap: 0 },
    blockPositionText: { color: c.foreground, fontSize: 12, fontWeight: "700" },
    blockRangeText: { color: c.foregroundMuted, fontFamily: "monospace", fontSize: 10.5 },
    diffHeaderStrip: { backgroundColor: withAlpha(c.accent, 0.07), borderRadius: 6, paddingVertical: 4, paddingHorizontal: 8, flexDirection: "row", alignItems: "center", gap: 8, flexWrap: "wrap" },
    diffHeaderRange: { fontFamily: "monospace", color: c.foreground, fontSize: compact ? 10.5 : 11 },
    diffLayoutRow: { flexDirection: "row", alignItems: "center", gap: 8, flexWrap: "wrap" },
    diffHeaderContext: { fontFamily: "monospace", color: c.accent, fontSize: compact ? 10.5 : 11, fontWeight: "600" },
    diffBox: { borderWidth: 1, borderColor: withAlpha(c.foregroundMuted, 0.16), borderRadius: 8, overflow: "hidden" },
    diffScroll: { maxHeight: compact ? 256 : 336, flexGrow: 0, flexShrink: 0 },
    diffScrollContent: { paddingVertical: 4, gap: 8 },
    diffColHeader: { paddingVertical: 6, paddingHorizontal: 8, backgroundColor: withAlpha(c.foreground, 0.025), borderBottomWidth: 1, borderBottomColor: withAlpha(c.foregroundMuted, 0.16) },
    diffColHeaderText: { color: c.foregroundMuted, fontSize: 9.5, fontWeight: "700", textTransform: "uppercase", letterSpacing: 0.6 },
    diffRow: { flexDirection: "row", alignItems: "stretch", paddingVertical: 1 },
    diffRowAdd: { backgroundColor: withAlpha(c.accent, 0.07) },
    diffRowDel: { backgroundColor: withAlpha(c.statusDanger, 0.07) },
    fileViewRowContext: { backgroundColor: withAlpha(c.foreground, 0.008) },
    fileViewRowAdd: { backgroundColor: withAlpha(c.accent, 0.18) },
    fileViewRowDel: { backgroundColor: withAlpha(c.statusDanger, 0.16) },
    fileViewRowActive: { borderLeftWidth: 2, borderLeftColor: c.accent },
    fileViewRowActiveAdd: { borderLeftColor: c.accent },
    fileViewRowActiveDel: { borderLeftColor: c.statusDanger },
    fileViewRowActiveContext: { borderLeftColor: c.foregroundMuted },
    fileViewDelText: { color: c.statusDanger, textDecorationLine: "line-through", opacity: 0.55 },
    fileSectionHeader: { flexShrink: 0, flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: compact ? 12 : 14, paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: withAlpha(c.foregroundMuted, 0.12) },
    fileViewNotice: { backgroundColor: withAlpha(c.accent, 0.07), borderRadius: 6, paddingVertical: 6, paddingHorizontal: 8, gap: 4 },
    fileViewNoticeText: { color: c.accent, fontSize: 11, fontWeight: "600", lineHeight: 15 },
    diffCell: { flex: 1, paddingVertical: 1 },
    diffCellLeft: { borderRightWidth: 1, borderRightColor: withAlpha(c.foregroundMuted, 0.16) },
    diffCellAdd: { backgroundColor: withAlpha(c.accent, 0.08) },
    diffCellDel: { backgroundColor: withAlpha(c.statusDanger, 0.08) },
    fileSectionHeaderText: { color: c.foreground, fontSize: compact ? 13.5 : 15, lineHeight: compact ? 19 : 21, fontWeight: "800", letterSpacing: 0.2 },
    diffCellContext: { backgroundColor: withAlpha(c.foreground, 0.015) },
    diffCellEmpty: { backgroundColor: withAlpha(c.foreground, 0.01) },
    diffCellInner: { flexDirection: "row", alignItems: "flex-start" },
    diffLineNo: { fontFamily: "monospace", fontSize: compact ? 9 : 10, color: c.foregroundMuted, width: 38, flexShrink: 0, textAlign: "right", paddingRight: 6, lineHeight: compact ? 15 : 17, paddingTop: 1 },
    diffCode: { fontFamily: "monospace", fontSize: compact ? 10.5 : 11.5, lineHeight: compact ? 15 : 17, color: c.foreground, paddingRight: 6, flexShrink: 1 },
    diffSign: { width: 16, fontFamily: "monospace", fontWeight: "700", fontSize: compact ? 10.5 : 11.5, lineHeight: compact ? 15 : 17, textAlign: "center" },
    diffSignAdd: { color: c.accent },
    diffSignDel: { color: c.statusDanger },
    diffSignContext: { color: c.foregroundMuted },
    actionRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, alignItems: "center" },
    body: { color: c.foreground, fontSize: compact ? 12 : 13, lineHeight: compact ? 17 : 19 },
    muted: { color: c.foregroundMuted, fontSize: compact ? 12 : 13, lineHeight: compact ? 17 : 19 },
    label: { color: c.foregroundMuted, fontSize: compact ? 10 : 11, fontWeight: "700", textTransform: "uppercase", letterSpacing: 0.5 },
    scopeDesc: { color: c.foregroundMuted, fontSize: compact ? 11 : 12, lineHeight: 16 },
    group: { gap: 4 },
    groupLabel: { color: c.foregroundMuted, fontSize: 11, fontWeight: "700", textTransform: "uppercase", letterSpacing: 0.4 },
    analysis: { gap: 10 },
    analysisBlock: { gap: 8 },
    findingsDisclosure: { minHeight: controlHeight, flexShrink: 0, flexDirection: "row", alignItems: "center", gap: 8, paddingVertical: 4, borderTopWidth: 1, borderBottomWidth: 1, borderColor: withAlpha(c.foregroundMuted, 0.14) },
    findingsContent: { gap: 8, paddingVertical: 8 },
    analysisStale: { borderLeftWidth: 2, borderLeftColor: c.accent, backgroundColor: withAlpha(c.accent, 0.06), padding: 8 },
    analysisStaleText: { color: c.accent, fontSize: 11.5, fontWeight: "600", lineHeight: 16 },
    bulletRow: { flexDirection: "row", gap: 6, alignItems: "flex-start" },
    bulletDot: { color: c.foregroundMuted, fontSize: 12, lineHeight: 19 },
    bulletContent: { flex: 1, gap: 2 },
    rawReview: { fontFamily: "monospace", fontSize: 11.5, lineHeight: 17, color: c.foreground, borderLeftWidth: 2, borderLeftColor: withAlpha(c.foregroundMuted, 0.32), paddingLeft: 10 },
    reviewDock: { gap: 6, padding: 10, backgroundColor: withAlpha(c.accent, 0.045), borderTopWidth: 2, borderTopColor: withAlpha(c.accent, 0.55), borderBottomWidth: 1, borderBottomColor: withAlpha(c.foregroundMuted, 0.14) },
    dockHeader: { flexDirection: "row", alignItems: "center", gap: 8 },
    dockTitle: { flex: 1, minWidth: 0 },
    savedBody: { gap: 4, paddingVertical: 4, borderBottomWidth: 1, borderBottomColor: withAlpha(c.foregroundMuted, 0.14) },
    savedMetaRow: { flexDirection: "row", alignItems: "center", gap: 8, flexWrap: "wrap" },
    inputRow: { flexDirection: "row", alignItems: "center", gap: 8, flexWrap: "wrap" },
    input: { minHeight: controlHeight, borderWidth: 1, borderColor: withAlpha(c.foregroundMuted, 0.3), borderRadius: 7, paddingHorizontal: 10, paddingVertical: 8, color: c.foreground, fontSize: compact ? 12 : 13, backgroundColor: withAlpha(c.foreground, 0.02) },
    inputFlex: { flex: 1, minWidth: 140 },
    commentInput: { minHeight: 80, textAlignVertical: "top", paddingTop: 8 },
    commentFooter: { flexDirection: "row", alignItems: "center", gap: 8, flexWrap: "wrap" },
    anchorRow: { flex: 1, minWidth: 200, flexDirection: "row", alignItems: "center", gap: 8, flexWrap: "wrap" },
    anchorMeta: { flexShrink: 1, color: c.foregroundMuted, fontFamily: "monospace", fontSize: 10.5, lineHeight: 15 },
    statusText: { color: c.accent, fontSize: 11, lineHeight: 15, fontWeight: "600" },
    otherCommentsScroll: { maxHeight: 144, flexGrow: 0 },
    otherCommentRow: { gap: 5, paddingVertical: 8, borderTopWidth: 1, borderTopColor: withAlpha(c.foregroundMuted, 0.14) },
    modalBackdrop: { flex: 1, backgroundColor: withAlpha(c.foreground, 0.45) },
    drawerBackdrop: { flex: 1, alignItems: compact ? "stretch" : "flex-end", backgroundColor: withAlpha(c.foreground, 0.45) },
    drawer: { width: "100%", maxWidth: compact ? undefined : 640, height: "100%", backgroundColor: c.surface0, borderLeftWidth: compact ? 0 : 1, borderLeftColor: withAlpha(c.foregroundMuted, 0.22) },
    centeredModalWrap: { flex: 1, justifyContent: "center", alignItems: "center", padding: compact ? 8 : 24, backgroundColor: withAlpha(c.foreground, 0.45) },
    centeredModal: { width: "100%", maxWidth: compact ? undefined : 680, maxHeight: compact ? "96%" : "88%", backgroundColor: c.surface0, borderWidth: 1, borderColor: withAlpha(c.foregroundMuted, 0.22), borderRadius: compact ? 10 : 12, overflow: "hidden" },
    modalHeader: { minHeight: compact ? 52 : 56, flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: compact ? 12 : 16, borderBottomWidth: 1, borderBottomColor: withAlpha(c.foregroundMuted, 0.16) },
    modalTitle: { flex: 1, color: c.foreground, fontSize: compact ? 15 : 17, lineHeight: compact ? 20 : 23, fontWeight: "700" },
    modalBody: { padding: compact ? 12 : 16, gap: 16 },
    modalSection: { gap: 10, paddingBottom: 16, borderBottomWidth: 1, borderBottomColor: withAlpha(c.foregroundMuted, 0.14) },
    queueIdentity: { gap: 3 },
    queueGroup: { gap: 8, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: withAlpha(c.foregroundMuted, 0.14) },
    queueFile: { gap: 6, paddingTop: 8, paddingLeft: compact ? 8 : 12 },
    queueComment: { gap: 3, paddingLeft: 10, borderLeftWidth: 2, borderLeftColor: withAlpha(c.accent, 0.35) },
    agentRow: { gap: 6, paddingVertical: 10, borderTopWidth: 1, borderTopColor: withAlpha(c.foregroundMuted, 0.14) },
    agentSelectRow: { flexDirection: "row", alignItems: "center", gap: 8, paddingVertical: 8, paddingHorizontal: 10, borderWidth: 1, borderColor: withAlpha(c.foregroundMuted, 0.16), borderRadius: 8 },
    agentSelectRowActive: { borderColor: withAlpha(c.accent, 0.55), backgroundColor: withAlpha(c.accent, 0.06) },
    agentSelectMarkActive: { color: c.accent, fontSize: 14, lineHeight: 18 },
    agentSelectMarkIdle: { color: c.foregroundMuted, fontSize: 14, lineHeight: 18 },
    routeFile: { color: c.foreground, fontSize: compact ? 12 : 12.5, fontWeight: "600" },
    routeMeta: { color: c.foregroundMuted, fontSize: compact ? 10.5 : 11, lineHeight: 15 },
    feedbackSent: { color: c.accent, fontSize: 11, lineHeight: 15, fontWeight: "600" },
    feedbackError: { color: c.statusDanger, fontSize: 11, lineHeight: 15 },
    emptyState: { gap: 8, paddingVertical: 24 },
    loadingTrack: { height: 2, borderRadius: 1, backgroundColor: withAlpha(c.accent, 0.12), overflow: "hidden", width: "60%", alignSelf: "center" },
    loadingFill: { width: "45%", height: 2, borderRadius: 1, backgroundColor: withAlpha(c.accent, 0.55) },
    empty: { color: c.foregroundMuted, fontSize: compact ? 12.5 : 14, paddingVertical: compact ? 16 : 24, textAlign: "center" },
  } as const;
}

export type PanelStyles = ReturnType<typeof buildPanelStyles>;
